services:
  fastapi-app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - APP_ACCESS_KEY=${APP_ACCESS_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TOKEN_LOCUST_TEST=${JWT_TOKEN_LOCUST_TEST}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - TRACE_SERVICE_NAME=${TRACE_SERVICE_NAME}
      - TRACE_ENABLED=${TRACE_ENABLED}
      - TRACE_INSECURE=${TRACE_INSECURE}
      - TRACE_USE_CREDENTIALS=${TRACE_USE_CREDENTIALS}
      - TRACE_TOKEN=${TRACE_TOKEN}
      - TRACE_SAMPLE_RATE=${TRACE_SAMPLE_RATE}
      - LOGGING_NAME=${LOGGING_NAME}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - LOGGING_HTTP_CLIENT_ENABLE=${LOGGING_HTTP_CLIENT_ENABLE}
      - LOGGING_CONSOLE_ENABLE=${LOGGING_CONSOLE_ENABLE}
      - LOGGING_FORMATTER=${LOGGING_FORMATTER}
      - LOGGING_FILE_ENABLE=${LOGGING_FILE_ENABLE}
      - LOGGING_FILE_PATH=${LOGGING_FILE_PATH}
      - LOGGING_OTLP_ENABLE=${LOGGING_OTLP_ENABLE}
      - LOGGING_OTLP_ENDPOINT=${LOGGING_OTLP_ENDPOINT}
      - LOGGING_OTLP_INSECURE=${LOGGING_OTLP_INSECURE}
      - LOGGING_OTLP_USE_CREDENTIALS=${LOGGING_OTLP_USE_CREDENTIALS}
      - LOGGING_USE_SSL_CERTIFICATE=${LOGGING_USE_SSL_CERTIFICATE}
      - LOGGING_TOKEN=${LOGGING_TOKEN}
      - LOGGING_TYPE=${LOGGING_TYPE}
      - LOGGING_SLACK_ENABLE=${LOGGING_SLACK_ENABLE}
      - SLACK_API_BOT_DEV_INFORMER_TOKEN=${SLACK_API_BOT_DEV_INFORMER_TOKEN}
      - SLACK_APP_NAME=${SLACK_APP_NAME}
      - SLACK_APP_TYPE=${SLACK_APP_TYPE}
      - SERVICE_NAME=${SERVICE_NAME}
      - SLACK_LOG_CHANNEL_ID=${SLACK_LOG_CHANNEL_ID}
      - METRICS_ENABLE=${METRICS_ENABLE}
      - METRICS_USE_CREDENTIALS=${METRICS_USE_CREDENTIALS}
      - METRICS_USE_SSL_CERTIFICATE=${METRICS_USE_SSL_CERTIFICATE}
      - METRICS_TOKEN=${METRICS_TOKEN}
      - METRICS_OTLP_ENDPOINT=${METRICS_OTLP_ENDPOINT}
      - METRICS_OTLP_INSECURE=${METRICS_OTLP_INSECURE}
      - METRICS_SERVICE_NAME=${METRICS_SERVICE_NAME}
      - METRICS_LIBRARY_NAME=${METRICS_LIBRARY_NAME}
      - METRICS_LIBRARY_VERSION=${METRICS_LIBRARY_VERSION}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./logs:/app/logs
    networks:
      - test-fastapi-sql-network

networks:
  test-fastapi-sql-network:
    external: true
