version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - APP_ACCESS_KEY=${APP_ACCESS_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    networks:
      - test-fastapi-sql-network

networks:
  test-fastapi-sql-network:
    external: true
